env:
  global:
    secure: KDSF6pX0GDzXz0PlQ6qW1xmnnvJHcDQWZzIN6yqIE73r80fUwoHglNUS9NCiDX9Rm5S79iu6fPSEAudTDJEP/KfDyjFueULiB9nAOS746DPPEzm3YIuYijNLuNaHno5tpJTmsog4NO2XxOw3NHRJ9LhqDKyZs2HjxEvpIWLzrJLENJSE0wYP2sDQNhGodAftPP/N6YxwN/OWEdBbK5wk+YQScACXE2MbXY/qq9PcKPMfUrgiHuQFRG7SQ3yKkMjDiP2OEnG0pHpWaNDYtTDovdBgIk6hH4YL4ltWVhkIrGI2vnN49YnTTXWJGVuKfQkwvh6mG4VbIPW5tlPI0NniFuPXYQ8Qzrh9x9xu4oljVhVknIkN20Rt0h0KTXR0IefeQJNlb89dU64p9Xvq/uePc8qAamtc/QlrLHZNlA6+dq9xV6Z16B9iVjABvMR6GyWdI/22wRo8MuoqP2PlCfHG28VaANCXPTJ5JLd02weW5ErSIHwFGWvk8pWR+oLeunGP/jVoypGCi6TO2inKETROpSYG6qvJgT+Pk2NwExLHtUDTW0G8wCKBJCbaJY9J2KjzOTxL5AoxkwkmeXzbLn/SdRXyQbqfr1so/GkmGgo57mibCmOSsfe6CuGu8/OJTb8VHRtE1IwUavUUXUVD3zZICTydaHHvOCWMWwvQ/7U0Rso=

language: node_js
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
jobs:
  include:
    - stage: deploy
      on:
        tags: true
      node_js: lts/*
      script:
        - npm ci
        - npx expo publish
