name: Publish app to expo

on:
  push:
    branches:
      - master
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install nodejs
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      # Install all the dependencies using the cached packages
      - uses: c-hive/gha-npm-cache@v1
      
      - name: "Install node packages"
        run: npm install

      - uses: expo/expo-github-action@v5
        with:
          expo-packager: npm
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: Run tests
        run: npm test

      - name: Publish to expo
        run: expo publish