name: Publish app to expo

on:
  push:
    branches:
      - master
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Incorporate production API key
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        run: |
          sed -i "s/process.env.FIREBASE_API_KEY/\"${FIREBASE_API_KEY}\"/" "${GITHUB_WORKSPACE}/api/Firebase.js"

      # Install nodejs
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      # Install all the dependencies using the cached packages      
      - name: "Install node packages with caching"
        uses: bahmutov/npm-install@v1.6.0

      - uses: expo/expo-github-action@v5
        with:
          expo-packager: npm
          expo-token: ${{ secrets.EXPO_TOKEN }}

      # - name: Run tests
      #   run: npm test
      # We are skipping the tests for now (very clever thing to do)

      - name: Upload code coverage results
        uses: codecov/codecov-action@v1
        with:
          verbose: true

      - name: Publish to expo
        run: expo publish